sshpub_location: /home/nomi/.ssh/wipperhome_rsa.pub #the full path to your SSH public key ( e.g. /Users/username/.ssh/id_ed25519.pub )
# root_pw: ohr14TtxyvJiyxt5jR2V #root password that should be set
user_name: wipper #username for the created user
# user_pw: 9JB7MV2CBeqQ9XALSgzE #password for the new user
ssh_port: 1149 #port number for ssh
mail_to: laia.gdla@gmail.com  #the mail address where mails should be sent to
mail_from: wipperhome@gmail.com #the mail address where mails are sent from
mail_smtp_server: smtp.gmail.com #mail server, e.g. smtp.gmail.com
mail_pw: sjyv mseu udem pjux #password for the mail_from mail address
mail_port: 587 #the port where mails are sent to the mail server, e.g. 587
ansible_python_interpreter: /usr/bin/python3
