- name: Prepare lynis installation
  become: true
  block:
    - name: Download Cisofy GPG key
      ansible.builtin.get_url:
        url: https://packages.cisofy.com/keys/cisofy-software-public.key
        dest: /etc/apt/trusted.gpg.d/cisofy-software-public.key
        owner: root
        group: root
        mode: '0644'

    - name: Add Cisofy GPG key
      ansible.builtin.apt_key:
        file: /etc/apt/trusted.gpg.d/cisofy-software-public.key

    - name: Add Cisofy Lynis repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/cisofy-lynis.list
        line: "deb https://packages.cisofy.com/community/lynis/deb/ stable main"
        create: true
        owner: root
        group: root
        mode: '0644'

# - name: Prepare lynis installation
#   become: true
#   ansible.builtin.shell: |
#     wget -O - https://packages.cisofy.com/keys/cisofy-software-public.key | sudo apt-key add -
#     echo "deb https://packages.cisofy.com/community/lynis/deb/ stable main" | sudo tee /etc/apt/sources.list.d/cisofy-lynis.list

- name: Update and upgrade
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install lynis
  become: true
  ansible.builtin.apt:
    name: lynis
    state: present

- name: Update and run first lynis audit
  become: true
  register: lynis
  ansible.builtin.shell: |
    lynis update info
    set -o pipefail
    lynis audit system | ansi2html -l > /tmp/lynis-report.html
    echo "First Lynis report see attachment" | mail -A /tmp/lynis-report.html -s "Lynis report" {{ mail_to }}
  args:
    executable: /bin/bash
  changed_when: lynis.rc != 0
