- name: Main-Playbook
  hosts: wipperhome
  remote_user: "{{ user_name }}"
  gather_facts: true
  vars_files: ./group_vars/variables.yml
  become: true
  # become_method: sudo
  become_user: root

  roles:
    - packages
    - ssh
    - password-quality
    - unattended-upgrades
    - firewall
    - mail
    - clamav
    - rkhunter
    - auditd
    - lynis
