- name: Restart psad service
  become: true
  ansible.builtin.service:
    name: psad
    state: restarted

- name: Restart fail2ban service
  become: true
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart sshd service
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
