- name: Update and upgrade
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - host
      - kbtin
      - ntp
      - libpam-pwquality
      - unattended-upgrades
      - apt-listchanges
      - apticron
      - ufw
      - psad
      - fail2ban
      - msmtp
      - msmtp-mta
      - mailutils
      - clamav
      - clamav-freshclam
      - clamav-daemon
      - rkhunter
      - auditd
      - audispd-plugins
    state: present
