- name: Configure mail settings
  become: true
  ansible.builtin.blockinfile:
    path: /etc/msmtprc
    block: |
      defaults
      port {{ mail_port }}
      tls on
      tls_trust_file /etc/ssl/certs/ca-certificates.crt
      account {{ mail_from }}
      host {{ mail_smtp_server }}
      set_from_header on
      from {{ mail_from }}
      auth on
      user {{ mail_from }}
      password {{ mail_pw }}
      account default: {{ mail_from }}
      aliases /etc/aliases
      logfile /var/log/msmtp
    create: true
    mode: '640'
  register: mail_settings

- name: Chmod mail config file
  become: true
  ansible.builtin.file:
    path: /etc/msmtprc
    group: msmtp
    mode: '640'
  register: chmod_mail_config

- name: Configure mail settings pt. 2
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/aliases
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: true
    mode: '640'
  loop:
    - { regexp: '^root:', line: 'root: {{ mail_to }}' }
    - { regexp: '^default:', line: 'default: {{ mail_to }}' }
  register: aliases_settings

- name: Configure mail settings pt. 3
  become: true
  ansible.builtin.lineinfile:
    path: /etc/mail.rc
    regexp: '^set sendmail'
    line: 'set sendmail="/usr/bin/msmtp -t"'
    create: true
    mode: '640'
  register: mail_rc_settings

- name: Determine if any changes occurred
  become: true
  ansible.builtin.set_fact:
    any_changes: >
      {{
        mail_settings.changed or
        chmod_mail_config.changed or
        aliases_settings.changed or
        mail_rc_settings.changed
      }}
    notify: Send a testmail
